---
- name: Create sysadmin group
  group: name=sysadmin gid=2000
  
- name: Create sysadmin user
  user: name=sysadmin shell=/bin/bash uid=2000 group=sysadmin

- name: Create .ssh directory for sysadmin user
  file: path=/home/sysadmin/.ssh state=directory owner=sysadmin mode=0700 group=sysadmin
  
- name: Copy authorized_keys into place.
  copy: src=authorized_keys dest=/home/sysadmin/.ssh/authorized_keys mode=0400 group=sysadmin owner=sysadmin

- name: Copy sshd config.
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- name: Restart sshd
  service: name=ssh start=restarted
